name: Jumper Release

run-name: Release Process for ${{ github.ref }} (${{ github.sha }})

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  BUILD_IS_VERSIONED: ${{ startsWith(github.ref, 'refs/tags/v') }}

  WIN_SDK_VERSION: "10.0.26100.0"

  JANET_VERSION: "1.39.1"
  JANET_DIR: "${{ github.workspace }}\\janet"
  JANET_PATH: "${{ github.workspace }}\\janet\\Library"
  JANET_SOURCE_PATH: "${{ github.workspace }}\\janet_src"
  JANET_BINPATH: "${{ github.workspace }}\\janet\\bin"
  JANET_HEADERPATH: "${{ github.workspace }}\\janet\\C"
  JANET_LIBPATH: "${{ github.workspace }}\\janet\\C"
  JANET_MANPATH: "${{ github.workspace }}\\janet\\docs"

  JPM_VERSION: "d93b7c243645d31410a81fb9ab8f7a5e5608f0d0"
  JPM_DIR: "${{ github.workspace }}\\jpm"
  JPM_CMD: "${{ github.workspace }}\\janet\\bin\\janet.exe ${{ github.workspace }}\\janet\\bin\\jpm"

  JUMPER_DIR: "${{ github.workspace }}\\jumper"

  MSI_INSTALL_SCRIPT: "${{ github.workspace }}\\jumper\\.github\\workflows\\install_janet_msi.ps1"

jobs:
  Jumper-Release:
    permissions:
      contents: write  # For releases

    runs-on: windows-2022

    steps:
      - run: echo "Working in directory ${{ github.workspace }}."

      - name: Checkout Jumper Source
        uses: actions/checkout@v4
        with:
          repository: agent-kilo/jumper
          path: ${{ env.JUMPER_DIR }}
          ref: ${{ github.sha }}

      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
        with:
          arch: x64
          sdk: ${{ env.WIN_SDK_VERSION }}

      - name: Checkout Janet Source
        uses: actions/checkout@v4
        with:
          repository: janet-lang/janet
          path: ${{ env.JANET_SOURCE_PATH }}
          ref: v${{ env.JANET_VERSION }}

      - name: Download Janet Installer
        uses: robinraju/release-downloader@v1.10
        with:
          repository: janet-lang/janet
          tag: v${{ env.JANET_VERSION }}
          fileName: janet-${{ env.JANET_VERSION }}-windows-x64-installer.msi
          out-file-path: ${{ github.workspace }}

      - name: Install Janet
        run: powershell -file "${{ env.MSI_INSTALL_SCRIPT }}" -msi_file janet-${{ env.JANET_VERSION }}-windows-x64-installer.msi -app_folder "${{ env.JANET_DIR }}"

      - name: Checkout JPM Source
        uses: actions/checkout@v4
        with:
          repository: janet-lang/jpm
          path: ${{ env.JPM_DIR }}
          ref: ${{ env.JPM_VERSION }}

      - name: Bootstrap JPM
        working-directory: ${{ env.JPM_DIR }}
        run: ${{ env.JANET_DIR }}\bin\janet.exe ${{ env.JPM_DIR }}\bootstrap.janet

      - name: JPM show-paths
        run: ${{ env.JPM_CMD }} show-paths

      - name: Show Janet Installation
        working-directory: ${{ env.JANET_DIR }}
        run: tree /f /a

      - name: Jumper Deps
        working-directory: ${{ env.JUMPER_DIR }}
        run: ${{ env.JPM_CMD }} --update-pkgs -l deps

      - name: Gather VCS version info for Jumper
        working-directory: ${{ env.JUMPER_DIR }}
        run: ${{ env.JPM_CMD }} -l run vcs-version

      - name: Build Jumper
        working-directory: ${{ env.JUMPER_DIR }}
        run: ${{ env.JPM_CMD }} -l build

      - name: SHA256 Checksum for Jumper.exe
        working-directory: ${{ env.JUMPER_DIR }}\build
        run: $(CertUtil -hashfile jumper.exe SHA256)[1] -replace " ","" > jumper.exe.sha256

      - name: List Built Artifacts
        run: dir ${{ env.JUMPER_DIR }}\build

      - name: Upload Built Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jumper-${{ github.ref_name }}-${{ github.sha }}
          path: |
            ${{ env.JUMPER_DIR }}\build\*.exe
            ${{ env.JUMPER_DIR }}\build\*.exe.sha256
          if-no-files-found: error
          retention-days: 7
          overwrite: true

      - name: Release Draft
        if: ${{ fromJSON(env.BUILD_IS_VERSIONED) }}
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            ./jumper/build/jumper.exe
            ./jumper/build/jumper.exe.sha256
